# -*- coding: utf-8 -*-
"""notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gM3C6lRsUBDvRtoBQHwn1pwVLeNkqK98

# Proyek Analisis Data: Bike Sharing Dataset
- **Nama:** Aulia Putri Fanani
- **Email:** liapuutri2007@gmail.com
- **ID Dicoding:** MC006D5X1464

## Menentukan Pertanyaan Bisnis

- Bagaimana pengaruh suhu (temp) terhadap jumlah peminjaman sepeda (cnt)?
- Apakah kecepatan angin (windspeed) yang tinggi berpengaruh terhadap  jumlah peminjaman sepeda?

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

# Mengumpulkan dan memuat dataset csv
day_df = pd.read_csv("/content/day.csv")
hour_df = pd.read_csv("/content/hour.csv")

# Menampilkan 5 baris pertama pada data frame day_dataset dan hour_dataset
day_df.head(10)

hour_df.head(10)

"""**Insight:**
- Dilakukan untuk memuat dan mendefinisikan dataset yang akan digunakan
- Mencoba menampilkan data 5 teratas pada dataset yang akan digunakan

### Assessing Data
Menilai data pada dataset dan melihat permasalahan data yang ada pada dataset
"""

# Memeriksa tipe data dataset
day_df.info()
hour_df.info()

# Memeriksa apakah terdapat missing value
day_df.isna().sum()

hour_df.isna().sum()

print("Jumlah duplikasi area 1: ", day_df.duplicated().sum())
print("Jumlah duplikasi area 2: ", hour_df.duplicated().sum())

# Menampilkan ringkasan parameter statistik
day_df.describe()

hour_df.describe()

"""**Insight:**
- Tidak ditemukan beberapa missing value
- Tidak ditemukan duplikasi data
- Dari hasil describe() dalam beberapa kolom kategorikal masing masing mempunyai nilai rentang yang sesuai
- dteday belum bertipe data date time

### Cleaning Data
"""

# Mendrop duplikasi data
day_df.drop_duplicates(inplace=True)
hour_df.drop_duplicates(inplace=True)

print("Jumlah duplikasi day_df : ", day_df.duplicated().sum())
print("Jumlah duplikasi hour_df : ", hour_df.duplicated().sum())

print("\nMissing Values day_df :\n", day_df.isna().sum())
print("\nMissing Values hour_df :\n", hour_df.isna().sum())

datetime_columns = ["dteday"]

for column in datetime_columns:
    day_df[column] = pd.to_datetime(day_df[column])

datetime_columns = ["dteday"]

for column in datetime_columns:
    hour_df[column] = pd.to_datetime(hour_df[column])

day_df.info()

hour_df.info()

"""**Insight:**
- Memastikan tidak adanya missing value
- Memastikan tidak adanya duplikasi data
- Mengubah tipe data dteday yang awalanya object menjadi datetime

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Melihat rangkuman parameter statistik dari dataset
day_df.describe()

# Melihat korelasi antara suhu dan jumlah peminjaman sepeda per jam untuk pertanyaan pertama
day_df[['temp','atemp', 'cnt']].corr()

# Melihat korelasi antara suhu dan jumlah peminjaman sepeda per hari untuk pertanyaan pertama
hour_df[['temp','atemp', 'cnt']].corr()

# Melihat korelasi antara kecepatan angin (windspeed) yang tinggi terhadap jumlah peminjaman sepeda tiap jamnnya

day_df[['windspeed', 'cnt']].corr()

hour_df[['windspeed', 'cnt']].corr()

# Membuat pivot tabel
day_df.groupby(["windspeed"]).agg({
    "cnt": "sum",
    "casual": "sum",
    "registered": "sum"
})

day_df.groupby(["temp"]).agg({
    "cnt": "sum",
    "casual": "sum",
    "registered": "sum"
}).sort_index(ascending=True)

# Melihat gabuangan dari hour_df dan day_df
all_df = pd.merge(
    left=day_df,
    right=hour_df,
    how="left",
    on="dteday"
)

all_df.head()

all_df.groupby(by="windspeed_x").agg({
    "cnt_x" : "sum",
    "cnt_y" : "sum",
    "casual_x" : "sum",
    "casual_y" : "sum",
    "registered_x" : "sum",
    "registered_y" : "sum",
})

all_df.groupby(by="temp_x").agg({
    "cnt_x" : "sum",
    "cnt_y" : "sum",
    "casual_x" : "sum",
    "casual_y" : "sum",
    "registered_x" : "sum",
    "registered_y" : "sum",
}).sort_index(ascending=True)

"""**Insight:**
- Menggunakan comman corr() atau korelasi yang digunakan untuk mengukur seberapa besar pengaruh antara dan suhu (tempt) dengan jumlah total peminjaman baik peminjam casual dan register. Terlihat derjat korelasi antara suhu dengan jumlah penyewa sepeda yang cukup positif. Sehingga mendapatkan asumsi bahwa semakin hangat cuaca, semakin banyak orang yang menyewa sepeda pada beberapa waktu namun tidak terbilang stabil
- Menggunakan comman corr() atau korelasi yang digunakan untuk mengukur seberapa besar pengaruh antara kecepatan angin (windspeed) dengan jumlah  total peminjaman baik peminjam casual dan register. Terlihat derajat korelasi antara kecepatan angin hari itu dengan jumlah peminjam sepeda yang memiliki korelasi negatif atau hampir netral. Sehingga mendapat asumsi bahwa banyak orang tidak terlalu peduli kondisi kecepatan angin saat ingin bersepeda pada titik tertentu
- Kedua asumsi diatas selaras juga ditampilkan pada pembuatan tabel pivot menggunakan gruop by yang mendukung hasil diatas.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Bagaimana pengaruh suhu (temp & atemp) terhadap jumlah peminjaman sepeda keseluruhan (cnt)?
"""

print(day_df.columns)

# Melakukan resampling data untuk menghitung rata-rata suhu serta total peminjaman dalam satu bulan
month_corr = day_df.resample(rule='ME').agg({
    "temp": "mean",
    "atemp": "mean",
    "cnt": "sum"
})
print("Korelasi Antar Variabel per Bulan:\n", month_corr.corr())

plt.figure(figsize=(10, 5))
plt.plot(month_corr.index,
         month_corr["cnt"],
         marker="o",
         color="b",
         label="Total Peminjaman")

plt.plot(month_corr.index,
         month_corr["temp"],
         marker="o",
         color="r",
         label="Rata-rata Suhu")

plt.title("Pengaruh Suhu dan Peminjaman Sepeda per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Nilai")
plt.xticks(rotation=45)
plt.legend()


plt.show()
'''Karena perubahan nilai perubahan suhu yang mempunyai skala yang jauh dengan peminjaman sepeda maka diperlukan
penyesuaian skala agar terlihat perubahan dan dampaknya yang selaras dengan perubahan jumlah peminjam sepeda '''

# Setelah disesuaikan
fig, ax1 = plt.subplots(figsize=(10, 5))

ax1.set_xlabel("Bulan")
ax1.set_ylabel("Total Peminjaman")
ax1.plot(month_corr.index,
         month_corr["cnt"],
         marker="o",
         color="b",
         label="Total Peminjaman")


ax2 = ax1.twinx()
ax2.set_ylabel("Rata-rata Suhu")
ax2.plot(month_corr.index,
         month_corr["temp"],
         marker="o",
         color="r",
         label="Rata-rata Suhu")

plt.title("Pengaruh Suhu dan Peminjaman Sepeda tiap bulan nya")
plt.show()

"""### Pertanyaan 2: Apakah kecepatan angin (windspeed) yang tinggi berpengaruh terhadap  jumlah peminjaman sepeda?"""

# Melakukan resampling data untuk menghitung rata-rata kecepatan angin serta total peminjaman dalam satu bulan
month_corr = day_df.resample(rule='ME').agg({
    "windspeed": "mean",
    "atemp": "mean",
    "cnt": "sum"
})
print("Korelasi Antar Variabel per Bulan:\n", month_corr.corr())

# Setelah disesuaikan
fig, ax1 = plt.subplots(figsize=(10, 5))

ax1.set_xlabel("Bulan")
ax1.set_ylabel("Total Peminjaman")
ax1.plot(month_corr.index,
         month_corr["cnt"],
         marker="o",
         color="b",
         label="Total Peminjaman")


ax2 = ax1.twinx()
ax2.set_ylabel("Rata-rata windspeed")
ax2.plot(month_corr.index,
         month_corr["windspeed"],
         marker="o",
         color="r",
         label="Rata-rata windspeed")

plt.title("Pengaru Kecepatan Angin dan Peminjaman Sepeda tiap bulan nya")
plt.show()

all_df.to_csv("all_data.csv", index=False)

"""**Insight:**
- Terlihat berdasarkan grafik dan analisis exploratory data diatas bahwa pada pertanyaan pertama terlihat bahwa suhu dapat turut memengaruhi jumlah peminjaman sepeda. Dikarenakan perbedaan skala yang begitu jauh, visualisasi data dibantu menggunakan twinx yang memungkinkan kita untuk dapat melihat plot data dengan 2 skala y yang berbeda sehingga memudahkan melihat pengaruhnya
- Begitu juga dengan pertanyaan kedua, terlihat hampir tidak ada pengaruh antara kecepatan angin dengan jumlah peminjaman sepeda sehingga tidak terlihat adanya adanya relasi pada 2 plot data pada visualisasi data diatas

## Analisis Lanjutan (Opsional)

## Conclusion

- Sehingga berdasarkan analisis data diatas dapat ditemukan bahwa ternyata kondisi suhu pada kondisi tertentu juga turut memengaruhi jumlah peminjaman sepeda. Sehingga semakin hangat cuaca maka akan semakin banyak orang yang berminat untuk meminjam sepeda
- Berdasarkan hasi analisis data diatas juga dapat ditemukan bahwa ternyata kondisi kecepatan angin tidak turut memengaruhi jumlah peminjam sepeda. Sehingga semakin cepat atau lambat kecepatan angin tidak sepenuhnya turut memengaruhi keinginan orang untuk meminjam sepeda.
"""